#!/bin/bash

modprobe vfio

driver=$1

videoid="10de 1b06"
audioid="10de 10ef"
videobusid="0000:08:00.0"
audiobusid="0000:08:00.1"


echo $videoid > /sys/bus/pci/drivers/$driver/new_id
echo $videobusid > /sys/bus/pci/devices/$videobusid/driver/unbind
echo $videobusid > /sys/bus/pci/drivers/$driver/bind
echo $videoid > /sys/bus/pci/drivers/$driver/remove_id

echo $audioid > /sys/bus/pci/drivers/$driver/new_id
echo $audiobusid > /sys/bus/pci/devices/$audiobusid/driver/unbind
echo $audiobusid > /sys/bus/pci/drivers/$driver/bind
echo $audioid > /sys/bus/pci/drivers/$driver/remove_id
