#!/bin/bash

export PATH="$PATH:/home/mabez/programs/cpuset"
LOG="/etc/libvirt/hooks/hook.log"
touch $LOG
CPUSET=/home/mabez/programs/cpuset/cset

# Direct all output to the logfile
exec > >(tee -a $LOG) 2>&1

VM_NAME=$1
VM_ACTION=$2
SCRIPT_PATH="/home/mabez/scripts/vfio"
VM_IP="192.168.0.13"
#VM_IP=$(ip addr show br0 | grep -Po 'inet \K[\d.]+')


# List of VMS where performance is critical
VMS_FOR_SHIELDING="win10 win10-nvme win10-kvmfr macos macosHS vfio-q35-win10 win10-nvme-q35-native"

# Ryzen 16 threads
TOTAL_CORES='0-15'
TOTAL_CORES_MASK=FFFF #0b1111111111111111
HOST_CORES='0-7'      # Cores reserved for host
HOST_CORES_MASK=FF00  #0b111111100000000
VIRT_CORES='8-15'     # Cores reserved for virtual machine(s)

prepare(){
	if [[ "${VMS_FOR_SHIELDING}" == *$VM_NAME* ]]; then
		echo "Running prepare for $VM_NAME" >> $LOG
		rc-service ckb-daemon stop
		if df | grep -q storage; then
                   umount /storage || exit 1 # dont start the VM if we fail to unmount the fs!
		fi
                sync
		echo 3 > /proc/sys/vm/drop_caches
		echo 1 > /proc/sys/vm/compact_memory
		sync
		$SCRIPT_PATH/huge_pages.sh 1
		# Turn off our display that we are using for the VM!
		su mabez -c "DISPLAY=:0 xrandr --output DVI-0 --off"
	fi
	# All VM's need networking
        $SCRIPT_PATH/virt_net enp6s0
}

start(){
	if [[ "${VMS_FOR_SHIELDING}" == *$VM_NAME* ]]; then
		echo "$(timestamp) $VM_NAME is being shielded" >> $LOG
		# Run custom scripts
		echo "Synergy: Connecting to $VM_IP"
		su mabez -c "synergyc $VM_IP"
		# reset a USB device that causes issues

		# Optimize perf
		shield_vm
		# Reduce VM jitter: https://www.kernel.org/doc/Documentation/kernel-per-CPU-kthreads.txt
	    sysctl vm.stat_interval=120
	    # sysctl -w kernel.watchdog=0
	    # the kernel's dirty page writeback mechanism uses kthread workers. They introduce
	    # massive arbitrary latencies when doing disk writes on the host and aren't
	    # migrated by cset. Restrict the workqueue to use only cpu 0.
	    echo $HOST_CORES_MASK > /sys/bus/workqueue/devices/writeback/cpumask
	    echo $HOST_CORES_MASK > /sys/devices/virtual/workqueue/cpumask
	    # THP can allegedly result in jitter. Better keep it off.
	    echo never > /sys/kernel/mm/transparent_hugepage/enabled
	    echo never >/sys/kernel/mm/transparent_hugepage/defrag

	    # Force P-states to P0
	    # echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
	    echo 0 > /sys/bus/workqueue/devices/writeback/numa
	fi
}

stop(){
	if [[ "${VMS_FOR_SHIELDING}" == *$VM_NAME* ]]; then
		unshield_vm
		sleep 1 # make sure threads are moved before trying to reinit hardware (can cause some issues)
	    sysctl vm.stat_interval=1
	    # sysctl -w kernel.watchdog=1
	    echo always > /sys/kernel/mm/transparent_hugepage/enabled
	    #echo powersave | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
	    echo 1 > /sys/bus/workqueue/devices/writeback/numa
		echo $TOTAL_CORES_MASK > /sys/bus/workqueue/devices/writeback/cpumask
	    echo $TOTAL_CORES_MASK > /sys/devices/virtual/workqueue/cpumask
		
		# Run our tear down scripts
		$SCRIPT_PATH/huge_pages.sh 0
		rc-service ckb-daemon start
		killall synergyc

		mount /storage

		# re-enable 144hz monintor - bash magic to run this asynchronously, so we dont hang if we have switched inputs
		bash -c "su mabez -c 'DISPLAY=:0 /home/mabez/scripts/util/dual_144hz.sh </dev/null &>/dev/null &; disown'"
	fi
}

#
# Util
#

timestamp() {
  date +"[%T]"
}

shield_vm() {
    python2 $CPUSET set system -c $HOST_CORES
    python2 $CPUSET proc --move --fromset=root --toset=system --threads --kthread --force
}

unshield_vm() {
	echo "$(timestamp)Unshielded $VM_NAME" >> $LOG
	python2 $CPUSET set -d system
	# cset shield --reset
}

#
# Catch libvirt actions
#
if [[ $VM_ACTION == 'prepare' ]];
then
	prepare
fi
if [[ $VM_ACTION == 'started' ]];
then
	start
fi
if [[ $VM_ACTION == 'stopped' ]];
then
	stop
fi

