#!/bin/bash
#
# Author: Sebastiaan Meijer (sebastiaan@passthroughpo.st)
#
# Copy this file to /etc/libvirt/hooks, make sure it's called "qemu".
# After this file is installed, restart libvirt.
# From now on, you can easily add per-guest qemu hooks.
# Add your hooks in /etc/libvirt/hooks/qemu.d/vm_name/hook_name/state_name.
# For a list of available hooks, please refer to https://www.libvirt.org/hooks.html
#
#   Logging modifications: Scott Mabin (@mabezdev)
#

LOG="/etc/libvirt/hooks/hook.log"
touch $LOG

# Direct all output to the logfile
exec > >(tee -a $LOG) 2>&1

GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

BASEDIR="$(dirname $0)"

HOOKPATH="$BASEDIR/qemu.d/$GUEST_NAME/$HOOK_NAME/$STATE_NAME"

set -e # If a script exits with an error, we should as well.

echo "Libvirt event for $GUEST_NAME: $HOOK_NAME/$STATE_NAME"

if [ -f "$HOOKPATH" ]; then
    eval \""$HOOKPATH"\" "$@"
elif [ -d "$HOOKPATH" ]; then
    while read file; do
        echo "Executing hook: $file"
        eval \""$file"\" "$@"
    done <<< "$(find -L "$HOOKPATH" -maxdepth 1 -type f -executable -print;)"
fi

