#!/bin/bash

while getopts p:t:c:e: option
do
 case "${option}"
 in
 t) TYPE=${OPTARG};;
 p) REPO_PATH=${OPTARG};;
 e) EXPORT_PATH=${OPTARG};;
 c) CUSTOM_BK_PATHS=${OPTARG};; # NYI
 esac
done

if [[ -z "$REPO_PATH" ]]; then
    echo "Invalid path, usage: -p /path/to/borg/repo"
    exit 1
fi


case $TYPE in
    rootfs) BK_PATHS="/etc /root /var /usr/local /usr/src/linux/.config";;
    home) BK_PATHS="/home/mabez" ;;
    full) BK_PATHS="/" ;;
    *) echo "-t must be 'rootfs' or 'home' or 'full'" 
       exit 1 ;;
esac
    
LOG="/var/log/backup-$TYPE.log"
# clean log before running
echo "" -n > $LOG
exec > >(tee -a $LOG) 2>&1

echo "Using repo path: $REPO_PATH. Initialing a $TYPE backup."

# Setting this, so the repo does not need to be given on the commandline:
#export BORG_REPO=ssh://username@example.com:2022/~/backup/main

# Setting this, so you won't be asked for your repository passphrase:
export BORG_PASSPHRASE='mabez'
# or this to ask an external program to supply the passphrase:
#export BORG_PASSCOMMAND='pass show backup'

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
now () { date -u +"%Y-%m-%dT%H:%M:%S"; }
notify () { su mabez -c "DISPLAY=:0 notify-send -t 3600000 \"$TYPE backup\" \"$1\""; }
web_sync () { 
    info "Syncing to gdrive"
    notify "Pushing to remote"
    # limit to upload speed
    rclone --bwlimit 6M -P --stats 30s --config /home/mabez/.config/rclone/rclone.conf move --create-empty-src-dirs $EXPORT_PATH gdrive:/
    # prune old backups
    rclone --config /home/mabez/.config/rclone/rclone.conf --min-age 21d delete gdrive:/
}
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup of $BK_PATHS"
notify "started..."
info "Mounting /backups"
# Backup the most important directories into an archive named after
# the machine this script is currently running on:
# When 2TB is installed start backing up VMS?

# we do this to acquire the 'lock' such that we wait for other scripts to finish
# wait up to 15 minutes
borg info $REPO_PATH --lock-wait 3600


ARCHIVE_NAME="$TYPE-$(hostname)-$(now)"

borg create                         \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --patterns-from /home/mabez/scripts/backup/patterns.txt \
                                    \
    $REPO_PATH::$ARCHIVE_NAME       \
    $BK_PATHS

backup_exit=$?

info "Pruning repository"

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-' prefix is very important to
# limit prune's operation to this machine's archives and not apply to
# other machines' archives also:

borg prune $REPO_PATH                         \
    --list                          \
    --prefix "$TYPE-$(hostname)"       \
    --show-rc                       \
    --keep-daily    5               \

# --keep-weekly   1               \
# --keep-monthly  1               \

prune_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 1 ];
then
    info "Backup and/or Prune finished with a warning"
    notify "exited with code: ${global_exit}"
fi

if [ ${global_exit} -gt 1 ];
then
    info "Backup and/or Prune finished with an error"
    notify "exited with code: ${global_exit}"
fi


if [[ ! -z "$EXPORT_PATH" ]]; then
    echo "Exporting $ARCHIVE_NAME to $EXPORT_PATH"
    mkdir -p $EXPORT_PATH
    borg export-tar $REPO_PATH::$ARCHIVE_NAME "$EXPORT_PATH/$ARCHIVE_NAME.tar.gz"
    web_sync
fi

info "Unmounting /backups"
info "Backup complete."
notify "Backup complete."

exit ${global_exit}
